name: Renew wildcard certificate if it expires soon
on:
  workflow_dispatch:
  schedule:
    # Daily at 16:00 UTC
    - cron: "16 0 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
  CERT_PFX_BASE64: ${{ secrets.WILDCARD_PFX_BASE64 }}
  CERT_PWD: ${{ secrets.WILDCARD_PFX_PWD }}
  CERT_EMAIL: "jeroen_bijlsma@yahoo.com"
  CERT_DOMAIN: "*.dotnet-works.com"
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

jobs:
  renew_certs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Renew certificates"
        run: |-
          chmod +x ./renew_certs.sh
          bash ./renew_certs.sh
