name: Renew certificate if it expires soon
on:
  workflow_dispatch:
  schedule:
    # Daily at 16:00 UTC
    - cron: "0 16 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }} # a github token that can write repository secrets
  CERT_PFX_BASE64: ${{ secrets.CERT_PFX_BASE64 }} # stores the base64 encoded pfx file. Renew-certs sets this secret!
  CERT_PWD: ${{ secrets.CERT_PWD }} # the passphrase to use for the certificate (pfx file)
  CERT_EMAIL: "jeroen_bijlsma@yahoo.com" # the email address that is sent to Cloudflare, so Cloudflare can inform you when the certificate is expiring
  CERT_DOMAIN: "*.dotnet-works.com" # your custom domain
  CERT_STAGING: true # the Letsencrypt environment to use for issuing certificates. Set to true to use the Staging environment for testing
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }} # The Cloudflare (global) API key. This is used to verify if you own the domain you are requesting a certificate for

jobs:
  renew_certs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Renew certificates"
        run: |-
          chmod +x ./renew_certs.sh
          bash ./renew_certs.sh
